# NN config.
nn:
    hidden: 64
    res_blocks: 4
    pol_feats: 32
    val_feats: 3
    batch_size: 64

# MCTS config.
mcts:
    sim_lim: 30
    c: 0.5
    tau: 1
    rewards:
        win: 1.0
        lose: -1.0
        draw: 0.5

# Self play config.
self_play:
    cycles: 3
    playouts: 100
    epochs: 4
